package com.example.hospital_automation.ui.theme

import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF1B82E9)
val onPrimaryLight = Color(0xFFF3F6FA)
val primaryContainerLight = Color(0xFFDEDFF8)
val onPrimaryContainerLight = Color(0xFF1C1E4A)
//------Additional
val onPrimaryContainerBlueLight = Color(0xFF333783)
val onPrimaryContainerVariantLight = Color(0xFFB2B3C3)
val primaryDimmedLight = Color(0xFFBCC7D2)
val primaryContainerTransparentLight = Color(0xFFDEDFF8)
//---------------------------------------------------------------------------------
val secondaryLight = Color(0xFF348879)
val onSecondaryLight = Color(0xFFF6FCFB)
val secondaryContainerLight = Color(0xFFDEF8F0)
val onSecondaryContainerLight = Color(0xFF1E1D20)
val tertiaryLight = Color(0xFFB09A43)
val onTertiaryLight = Color(0xFFFCFAF6)
val tertiaryContainerLight = Color(0xFFF8F1DE)
val onTertiaryContainerLight = Color(0xFF2A2927)
val errorLight = Color(0xFFA43333)
val onErrorLight = Color(0xFFFDF7F7)
val errorContainerLight = Color(0x66F8DEDE) //40%
val onErrorContainerLight = Color(0xFF851919)
val backgroundLight = Color(0xFFF9F9FA)
val onBackgroundLight = Color(0xFF232329)
//------Additional
val onBackgroundVariantLight = Color(0xFF99999F)
val onBackgroundVariant2Light = Color(0xFFC1C1C2)
//---------------------------------------------------------------------------------
val surfaceLight = Color(0xFFEFF1FC)
val onSurfaceLight = Color(0xFF1C1B1E)
val outlineLight = Color(0xFF73707B)
val outlineVariantLight = Color(0xFFE1DCE8)
val surfaceContainerLowLight = Color(0xFFF2F2FA)
val surfaceContainerLight = Color(0xFFE6E8F0)
val surfaceContainerHighLight = Color(0xFFE6E8F0)
//------Additional
val onSurfaceContainerLight = Color(0xFF1D1C1F)
val onSurfaceContainerVariantLight = Color(0xFF5C5863)
val onSurfaceContainerVariant2Light = Color(0xFF918E97)
//---------------------------------------------------------------------------------


//Edit when needed
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F312A)
val inverseOnSurfaceLight = Color(0xFFF1F2E6)
val inversePrimaryLight = Color(0xFFB1D18A)
val surfaceDimLight = Color(0xFFDADBD0)
val surfaceBrightLight = Color(0xFFF9FAEF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceVariantLight = Color(0xFFEFF1FC)
val onSurfaceVariantLight = Color(0xFFEFF1FC)
val surfaceContainerHighestLight = Color(0xFFE2E3D8)


val primaryDark = Color(0xFFB1D18A)
val onPrimaryDark = Color(0xFF1F3701)
val primaryContainerDark = Color(0xFF354E16)
val onPrimaryContainerDark = Color(0xFFCDEDA3)
val secondaryDark = Color(0xFFBFCBAD)
val onSecondaryDark = Color(0xFF2A331E)
val secondaryContainerDark = Color(0xFF404A33)
val onSecondaryContainerDark = Color(0xFFDCE7C8)
val tertiaryDark = Color(0xFFA0D0CB)
val onTertiaryDark = Color(0xFF003735)
val tertiaryContainerDark = Color(0xFF1F4E4B)
val onTertiaryContainerDark = Color(0xFFBCECE7)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF12140E)
val onBackgroundDark = Color(0xFFE2E3D8)
val surfaceDark = Color(0xFF12140E)
val onSurfaceDark = Color(0xFFE2E3D8)
val surfaceVariantDark = Color(0xFF44483D)
val onSurfaceVariantDark = Color(0xFFC5C8BA)
val outlineDark = Color(0xFF8F9285)
val outlineVariantDark = Color(0xFF44483D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E3D8)
val inverseOnSurfaceDark = Color(0xFF2F312A)
val inversePrimaryDark = Color(0xFF4C662B)
val surfaceDimDark = Color(0xFF12140E)
val surfaceBrightDark = Color(0xFF383A32)
val surfaceContainerLowestDark = Color(0xFF0C0F09)
val surfaceContainerLowDark = Color(0xFF1A1C16)
val surfaceContainerDark = Color(0xFF1E201A)
val surfaceContainerHighDark = Color(0xFF282B24)
val surfaceContainerHighestDark = Color(0xFF33362E)

